[project]
name = "ncs-experiment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "opencv-python>=4.12.0.88",
    "openvino>=2025.3.0",
    "ultralytics>=8.3.203",
]

[tool.pyright]
venvPath = "."
venv = ".venv"
